<html>
<head>
<style>
body{
         background-image:url(sunrise.jpg)
         background-repeat:no-repeat;
         background-position:80%,100%;}
h1{
    background-color:black; color:white;
  }
div{
        border:1px solid black;
        background-color:lightblue;
   }
p{
    background-color:yellow; color:red;
  }
p.normal{
              font-style:normal;
            }
p.italic{
              font-style:italic;
          }
p.oblique{
                 font-style:oblique;
        }
</style>
</head>
<body>
<h1>Hello word!</h1>
<h1>CSS background-color example</h1>
<div>
this is a text inside a div element <br />
this paragraph has its own background color<br />
we are still in the div element
</div>
<p class="normal">this is a paragraph in normal style</p>
<p class="italic">this is a italic style</p>
<p class="oblique">this is a pragraph in oblique style</p?
</body>
</html> 
